import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Nav from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import {Inter} from "next/font/google";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "QuickNews",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Toaster richColors closeButton={true}/>
        <Providers>
          <Nav/>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
